### ISSUE TITLE
Taking date from photo/video filename instead of exif

### ISSUE THREAD

**Issue by Jarppi01** [ivandokov/phockup#11]
Since most of my photos / videos dont have exif info but are named like this `IMG_20160209_105114.jpg`
it would be helpfull to get date from filename.

**Comment by ivandokov** [comment]
Currently the date from filename is a backup option when the exif date is not available. 
If I understand correctly you are suggesting to make this option the primary one.

I am not sure that this is a good option because MOST of the DSLR photos are not using this name scheme by default and this will be waste of checks for each photo (using regex which is not very fast too).

**Comment by Jarppi01** [comment]
> If I understand correctly you are suggesting to make this option the primary one.

Yes, or atleast option.

> I am not sure that this is a good option because MOST of the DSLR photos are not using this name scheme by default and this will be waste of checks for each photo (using regex which is not very fast too).

I understand but i am not using this for DSLR photos, i am using this for photos taken with Phone.



I have been looking for this kind software for long time and would really appreciate if you would consider adding this as an option, anyways thanks for all the hard work! 👍

**Comment by ivandokov** [comment]
It is an option, but only if the EXIF data doesn't have date. 
Usually EXIF is considered the better option because the file name is really easy to be changed, but for EXIF you need some kind of software.

You can check the source [here](https://github.com/ivandokov/phockup/blob/master/phockup.py#L98) that I am parsing the exact same format as you requested `IMG_20160209_105114.jpg`
