### ISSUE TITLE
homebrew install missing python module dependency "tqdm"

### ISSUE THREAD

**Issue by stevehartwell** [ivandokov/phockup#170]
% phockup --help
```
Traceback (most recent call last):
  File "/Volumes/NoSave/Homebrew/bin/phockup", line 11, in <module>
    from src.phockup import Phockup
  File "/Volumes/NoSave/Homebrew/Cellar/phockup/1.9.1/src/phockup.py", line 11, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```
% pip3 install tqdm
`Successfully installed tqdm-4.64.1`
% phockup --help   
```
usage: phockup [-h] [-v] [-d DATE] [-m | -l] [-o] [-t] [-y] [-c 1-255]
               [--maxdepth 1-255] [-r REGEX] [-f DATE_FIELD]
               [--debug | --quiet | --progress] [--log LOG]
               [--file-type image|video] [--no-date-dir NO_DATE_DIR]
               [--skip-unknown]
               INPUTDIR OUTPUTDIR
```

**Comment by ivandokov** [comment]
I tried to fix this one for quite some time but I only wasted my time and nerves. 
Homebrew do not use pip but instead requires us to specify each dependency manually, including the hash. Like this:

```ruby 
  resource "tqdm" do
    url "https://files.pythonhosted.org/packages/c1/c2/d8a40e5363fb01806870e444fc1d066282743292ff32a9da54af51ce36a2/tqdm-4.64.1.tar.gz"
    sha256 "5f4f682a004951c1b450bc753c710e9280c5746ce6ffedee253ddbcbf54cf1e4"
  end
```

I did what I had to do by reading the docs and checking other python software formulas but got no success.
Looks like I'll need some assistance.

**Comment by demeesterroel** [comment]
I have a similar error - but working on ubuntu 22.04 - installed it using snap

% phockup --help
`Traceback (most recent call last):
  File "/snap/phockup/407/phockup.py", line 11, in <module>
    from src.phockup import Phockup
  File "/snap/phockup/407/src/phockup.py", line 9, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
`


%pip install tqdm
`Defaulting to user installation because normal site-packages is not writeable
Collecting tqdm
  Downloading tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 KB 1.4 MB/s eta 0:00:00
Installing collected packages: tqdm
Successfully installed tqdm-4.64.1
`

% phockup --help
`Traceback (most recent call last):
  File "/snap/phockup/407/phockup.py", line 11, in <module>
    from src.phockup import Phockup
  File "/snap/phockup/407/src/phockup.py", line 9, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
`
---
How can I help?  
Do you have instructions somewhere on how to setup my machine to debug ?

**Comment by ivandokov** [comment]
Yeah, snap is another beast we have to slay.
The snap setup requires update to match the newer versions of snap build process. I tried to tackle that one too but again it requried more time than I had and it is on hold for me at least.

**Comment by patsevanton** [comment]
Same issue

**Comment by ivandokov** [comment]
I finally fixed this https://github.com/ivandokov/homebrew-contrib/commit/1a704490b495abd8331650750acd79a013e135f8 !!!
