### ISSUE TITLE
Docker method creates unneccessary folders

### ISSUE THREAD

**Issue by JoshuaCrewe** [ivandokov/phockup#197]
This issue is very much to keep my memory on track. I am new to this tool and am working it out through testing.

When running the command via Docker extra folders are created in the mount point. These folders are called `input` and `output`. They don't seem to relate to anything as the Input and Output can be specified by the user and are specified as `Input` and `Output` in the documentation (note the capitals)

I think this is due to the Docker file declaring some Volumes that are not needed. To test this I used different volumes inside the container and it all worked fine :

```
sudo docker run -u 1000:1000 -v ~/path/to/storage:/dev/shm ivandokov/phockup:latest /dev/shm/Input /dev/shm/Output
```
This is an issue and not a PR becuase I am right at the end of a work day and don't want to lose track of what I have learnt. To confirm I would need to clone the repo and run the same tests based on an updated Dockerfile which is completely doable and I will find the time.

**Comment by JoshuaCrewe** [comment]
Looking at the entrypoint.sh it looks like the Volume mounts are there for the recurring docker command when a cron command is set. In which case it might be worth updating the documentation to `input` and `output` which would avoid some confusion. It would seem that when running as a continuous process these folder names are required (which is fine).

**Comment by ivandokov** [comment]
Ho be honest it's been awhile since I've used the Docker version and I'm not aware of the issue. 
It will be cool if the owner of Docker with Cron-related PR checks your report here @moritzfl.

**Comment by moritzfl** [comment]
When running phockup in Docker continuously with the CRON setting, it needs mappings of two folders on the host to know where to put the input and output. The continuous mode of Docker executions relies on Environment variables and volume mappings instead of direct parameters. Direct parameters are only used for single executions.

I guess that could be stated more explicitly in the Readme.

The example in the Readme shows the paths for those folders inside the docker container in the execution example:
```docker run -v ~/Pictures/input:/mnt/input -v ~/Pictures/output:/mnt/output -e "CRON=* * * * *" -e "OPTIONS=[PHOCKUP ARGUMENTS]" ivandokov/phockup:latest```

You are not forced to use the name "input" and "output" on your folders on the host machine but you need to map your folders to the folders where the Docker image expects them (i.e. /mnt/input and /mnt/output). So you could for example do the following:
```docker run -v ~/Pictures/In-With-My-Photos:/mnt/input -v ~/Pictures/Out-With-My-Photos:/mnt/output -e "CRON=* * * * *" -e "OPTIONS=[PHOCKUP ARGUMENTS]" ivandokov/phockup:latest```

I would expect that this resolves the issue and no unwanted folders are created.

**Comment by JoshuaCrewe** [comment]
I think updating the readme example for single execution to use `input` and `output` (lowercase) would  remove the initial unexpected behaviour. Maybe some additional information about not being required but will be created?

I can have a look in a PR if that's helpful?

**Comment by moritzfl** [comment]
I would rather not document anything about folders being created automatically because I would not encourage mounting just one folder to the phockup container instead of explicitly stating where input and output is on the host. 

If you disagree, feel free to add it to the documentation – I am not that invested in pushing my opinion here ;)

Creating the folders is something that phockup probably does because it gets passed /mnt/input and /mnt/output as input within the docker container.
If you only map a folder from your host to the /mnt folder, the folder might not have the subfolders input and output and thus phockup creates them. And as /mnt is mapped to your host, it will create those folders on the hosts filesystem.

**Comment by JoshuaCrewe** [comment]
This all moved very quickly. I saw the PR that was created and merged so good job! I think in the end, the example command for a one shot should have a lowercase `i` and a lowercase `o` for the input and output. I ran the command from the docs and got double the folders that were needed!
