### ISSUE TITLE
Traceback: Error in phockup.py?

### ISSUE THREAD

**Issue by Rudertier** [ivandokov/phockup#30]
Hello,

I'm unsure if this is an issue relate to your program, but when running the snap version of phockup I get this cryptic traceback:
```
$user@thinkpad ~ $ phockup ~/Dropbox/Kamera-Uploads/ $backupDrive/Pictures/ --date YYYY/MM_M

~/Dropbox/Kamera-Uploads/2017-06-04 11.03.04.jpgTraceback (most recent call last):
  File "/snap/phockup/67/lib/phockup/phockup.py", line 343, in <module>
    main(sys.argv[1:])
  File "/snap/phockup/67/lib/phockup/phockup.py", line 63, in main
    handle_file(os.path.join(root, filename), outputdir, dir_format, move_files)
  File "/snap/phockup/67/lib/phockup/phockup.py", line 235, in handle_file
    if sha256_checksum(source_file) == sha256_checksum(target_file):
  File "/snap/phockup/67/lib/phockup/phockup.py", line 281, in sha256_checksum
    with open(filename, 'rb') as f:
PermissionError: [Errno 13] Permission denied: '/media/julius/Backup/Pictures/2017/06_June/20170604-110304687693.jpg'
```
Do you have an Idea how to solve this issue? 
Best

**Comment by ivandokov** [comment]
This is too informative/developer friendly error message coming from snapd saying that it does not have permissions to access your `/media/julius` drive. 
It is weird that you do not have access since I have defined that the snap package requires `removable-media`. I'll have to take a look at this.
The temporary workaround is to move the files on your main hard drive and use it from there.

**Comment by ivandokov** [comment]
It turns out you have to give access to the `/media` explicitly with:
```
sudo snap connect phockup:removable-media
```
