### ISSUE TITLE
Skipping files without EXIF date

### ISSUE THREAD

**Issue by leoc** [ivandokov/phockup#79]
is it possible to skip files that have not date data and would land in the unknown folder?

I have many files that would not be identifiable upon the moment that they land in an unknown directory and the context of the original path would help me deciding which occasion and date I want to use for a fix.

**Comment by rwenz3l** [comment]
maybe do a `--dry-run` first and check what the output says?
You can also add datetime yourself using the file creation/mod dates with `exiv2` if you want to:

```
set_exif_date_to_file_date() {
  for f in ./*.jpg; do
    # Get Unix Timestamp (mtime)
    t=$(stat --printf '%Y' "${f}")
    # Convert to proper datetime
    d=$(date +'%Y-%m-%d %H:%M:%S' -d @${t})
    # Set DateTime from filestamp
    exiv2 -M"set Exif.Photo.DateTimeOriginal ${d}" "${f}"
    echo "Set ${f} to ${d}"
	done
}
```

**Comment by Avamander** [comment]
I concur with OP, I'd rather it not move images when there's no EXIF data. Something like `--no-unknown` would be nice.

**Comment by wgicio** [comment]
this would be a wonderful improvement, especially for really old photos which are getting dumped into the unknown folder

**Comment by imagesafari** [comment]
Better still, I'd love to be able to specify the "unknown" folder, and have it drop things into a folder structure that matches the source input folder structure to provide context as to where those photos originated.

**Comment by ivandokov** [comment]
I just want to note that few days ago I sorted again my photos archive (about 500GB) and I had more than 3000 photos in **unknown** and I simply ran phockup again but with different flags on the **unknown** folder only to sort most of the remaining photos. It is really rare to have photos with no data **at all**. Usually you have to check the data that `exiftool` provides and run phockup again with the correct options to handle the edge cases. In my case I had to use `-f FileModifyDate` flag because many of my photos under **unknown** had the correct date at this key.

**Comment by unapproachable** [comment]
Work in progress on this found here:

https://github.com/unapproachable/phockup/tree/feature/issue_79

I'll issue a PR soon, but wanted to put it up in case anyone was looking to test it.  This includes the test for the flag (`--skip-unknown`) in the harness.

I found need for this recently when I was processing a bunch of older images and their EXIF data was 'different'.  Moving the files to 'unknown' was detrimental because the source directory from the images (e.g., /photos/birthday_2004) contained a useful taxonomy to help decode which EXIF field to use (the ones from 2004...).  I'd almost go so far as to recommend we invert the logic to _only_ move the files if a flag (`--move-unknown`) is set.  However, to honor this issue request, I implemented the flag as specified.
