### ISSUE TITLE
Flag to overwrite existing file (same name) considering better quality (bigger size)

### ISSUE THREAD

**Issue by esppat** [ivandokov/phockup#82]
It would be very nice to allow a flag (with different options) to allow the overwrite of destination file if some conditions are met:
(would be nice for pictures AND videos)

- Same size in EXIF but file size is bigger than existing
- Bigger picture size in EXIF
- Same EXIF "quality", file size is different, picture is more recent (choose date-field to use)
- Possibility to move the overwritten file to a .../overwritten/... directory
- etc.

**Comment by ivandokov** [comment]
That's a good idea for a new feature. PRs are welcome!

**Comment by mruiz42** [comment]
I can look into this issue, but first I would like to clarify how exactly you can determine if they are low res/high res versions of a single image/video in particular. For example, they both have different checksums since their file contents differ, yet they are the same image (just a different format, cropped, etc.). How can we safely assume both files are altered copies? Is a date timestamp sufficient enough to assume they are the same image?
This feature is solely intended to keep the high res (RAW?) files separate from its compressed counterparts?

**Comment by ivandokov** [comment]
As I went through this issue again I came to the conclusion that this is not possible as the checksum of the files is going to be different and they are considered different files and not the same but smaller size.
If you have a way to detect the same file but with different quality feel free to reopen the issue.
